version: '3.8'
services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - stc

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    restart: always
    depends_on:
      - database
    networks:
      - stc
    environment:
      spring.datasource.url: 'jdbc:postgresql://database:5432/stc'
      spring.datasource.username: postgres
      spring.datasource.password: postgres


volumes:
  postgres-data:

networks:
  stc:
